title: 周一帆 (Yifan Zhou)
logo: /assets/img/logo.png
description: I am a master’s student in **Robotics, Systems, and Control** at **ETH Zürich**, passionate about robot learning, manipulation, and assistive systems. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
