# Site settings
title: "Yifan Zhou"
description: "Robotics MSc at ETH Zürich | Reinforcement Learning, Dexterous Manipulation, Assistive Systems"
url: "https://yifanzhou.github.io"
baseurl: ""

# Author
author:
  name: "Yifan Zhou"
  email: "yifzhou@ethz.ch"
  github: "YifanZhou99"
  linkedin: "yifan-zhou-robotics"
  affiliation: "ETH Zürich — Soft Robotics Lab"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Navigation
nav:
  - name: "About"
    link: "/"
  - name: "Projects"
    link: "/projects"
  - name: "Publications"
    link: "/publications"
  - name: "Blog"
    link: "/blog"

# Color and style
theme_color: "#00559D"  # ETH Zürich blue
markdown: kramdown
